### ISSUE TITLE
Wrong api result

### ISSUE THREAD

**Issue by cpromise** [satoshi-takano/OpenGraph#24]
First of all, I'm not a Navtive English speaker. So please excuse me.

When I try to use OpenGraph.fetch method with "https://www.github.com", I got result as below

```
OpenGraph.OpenGraphMetadata.image: "image/png", 
OpenGraph.OpenGraphMetadata.url: "IE=edge", 
OpenGraph.OpenGraphMetadata.site_name: "GitHub", 
OpenGraph.OpenGraphMetadata.title: "Build software better, together"])
```
I expect the result to be like this
```
.image = "https://assets-cdn.github.com/images/modules/open_graph/github-logo.png"
.url = "https://github.com"
```

I doubt the regular expression ```"<meta\\s.*?property=\"og:(\\w+?)\".*?/?>"```
However, I'm not good at regular expression,, So I couldn't fix it by myself.

**Comment by satoshi-takano** [comment]
@cpromise Thank you for your issue report. I fixed this issue.
https://github.com/satoshi-takano/OpenGraph/pull/25

**Comment by cpromise** [comment]
@satoshi-takano Thank you so much^^
