### ISSUE TITLE
Swift 4 Updates

### ISSUE THREAD

**Issue by Vortec4800** [satoshi-takano/OpenGraph#27]
It appears that there are a few very minor updates required for Swift 4 support. There is one method in the OpenGraphParser.swift file that was renamed from rangeAt() to range(at:). That's the only change necessary. I don't know if you want a PR for this or when you would want to implement it.

**Comment by satoshi-takano** [comment]
I'm going to update this library to support Swift4 this weekend. 🙏

**Comment by Vortec4800** [comment]
Great thanks!

**Comment by satoshi-takano** [comment]
merged #28.
