### ISSUE TITLE
Can `source` property be declared public?

### ISSUE THREAD

**Issue by hstdt** [satoshi-takano/OpenGraph#33]
I want to get the `source` dictionary, but `fileprivate` makes it impossible(including KVC). How about declaring this property public?

![image](https://user-images.githubusercontent.com/10215098/50064106-4ac65e00-01ea-11e9-98e5-0c149e20bb88.png)

**Comment by satoshi-takano** [comment]
@hstdt Sorry for late reply. It's ok to make the `source` property public. I'll update the property later. Or your pull request should be merged :) Thanks!
