### ISSUE TITLE
USA Today Links Returning No Open Graph Data

### ISSUE THREAD

**Issue by Innocuousjoe** [satoshi-takano/OpenGraph#39]
Getting zero metadata from [USA Today links like this one](https://www.usatoday.com/story/news/education/2020/02/27/college-accreditation-betsy-devos-education-department-house-committee-investigation-sd/4891749002/) despite there being og headers in the page source code.

Couldn't see anything immediately wrong with the regex, thoughts?

**Comment by satoshi-takano** [comment]
@Innocuousjoe 
Thanks for your report! I've fixed this issue with #40 and released version 1.2.1.

**Comment by Innocuousjoe** [comment]
@satoshi-takano My pleasure!  Really appreciate your diligence in maintaining this!
