### ISSUE TITLE
URL from web browser site not parsing sometimes 

### ISSUE THREAD

**Issue by scy0334** [satoshi-takano/OpenGraph#51]
Hi Satoshi! Thanks for this amazing library!

I'm having error while fetching metadata from specific website.
I'm trying to debug why following websites' metadata are not being fetched, but couldn't reason why. 

Also, I'm using "1.3.0" version.. Somehow I counldn't "pod install" version "1.3.1".

**Headers I'm passing**
`["User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 facebookexternalhit/1.1"]`

**Error Website:** 
https://news.naver.com/main/ranking/read.naver?mode=LSD&mid=shm&sid1=001&oid=011&aid=0003987466&rankingType=RANKING

**Comment by satoshi-takano** [comment]
@scy0334 
Sorry for my late reply. The reason why the site which you provided couldn't be extracted its OGP was its text encoding. And #52 is going to fix this problem and now you can introduce the changes by installing 1.4.0. Thanks.

**Comment by scy0334** [comment]
Thanks!
