### ISSUE TITLE
The operation couldn’t be completed. No space left on device

### ISSUE THREAD

**Issue by seankmg** [satoshi-takano/OpenGraph#53]
When opening the app, OpenGraph successfully fetches mutliple urls through the fetch function in app. 

After a pull to refresh this information is being updated through the same fetch function.

Since two weeks there is the problem that, if you pull to refresh, gives the OpenGraph error „The operation couldn‘t be completed. No space left on device.“
(The error seems to come up 90% of the times you try to pull to refresh the current view)

After gaining some feedback of beta users *it seems* that the problem mostly occurs on iPhone 11 devices. 

iPhone 12 and other devices seem to not show the error.

In every case there was more than enough free space on the device itself (in my case, iPhone 11 Pro Max, there were 50Gb of 256Gb still free). Also the memory monitor in Xcode showed that more than enough Ram for the app was available and not used.

After relaunching the app, fetching is again possible without a problem - until pull to refresh is engaged.

Is this problem already monitored?

**Comment by satoshi-takano** [comment]
I'm not sure why the error has occurred since OpenGraph doesn't use local storages to save its data. And I've not received any reports which seems to related to your problem for now.
