### ISSUE TITLE
New cocoapods update version 1.4.1 iOS 15 required. Missing @available(iOS 15.0, *)

### ISSUE THREAD

**Issue by Spencer-Villarreal** [satoshi-takano/OpenGraph#57]
I just updated through cocoapods and got hit with about 5 compile errors in 

File: URLSession.swift

public extension URLSession 

Error: "Concurrency is only available in iOS 15.0.0 or newer"

**Comment by satoshi-takano** [comment]
@Spencer-Villarreal 
Thanks for your report. Would you try using Xcode 13.2.1? Thanks.

**Comment by bevanchristian** [comment]
> I just updated through cocoapods and got hit with about 5 compile errors in
> 
> File: URLSession.swift
> 
> public extension URLSession
> 
> Error: "Concurrency is only available in iOS 15.0.0 or newer"

same xcode 13.1 error

**Comment by Spencer-Villarreal** [comment]
After updating to the newest version the error was fixed! Sorry for not getting back to you, but I am about to open another issue.
