### ISSUE TITLE
If the title has an apostrophe it instead shows "&#x27"

### ISSUE THREAD

**Issue by Spencer-Villarreal** [satoshi-takano/OpenGraph#58]
When I am using your pod to fetch the OG tags from a news article that has an apostrophe it shows an error with your method.

Version: 1.4.1
Used cocapods to install
Xcode version: 13.2.1
Device: iPhone 12 iOS 15.1

----- Example 1 -----
Should receive:
Jim Simons' RenTech fund nearly doubled its AMC stake

What I receive when using your pod:
Jim Simons&#x27; RenTech fund nearly doubled its AMC stake

https://markets.businessinsider.com/news/stocks/jim-simons-renaissance-technologies-rentech-amc-entertainment-gamestop-tesla-stock-2022-2?amp

----- Example 2 -----
Should receive:
Today's Stock Market News & Events: 12/8/2021

What I receive when using your pod:
Today&#39;s Stock Market News &amp; Events: 12/8/2021

https://www.schaeffersresearch.com/content/news/2021/12/08/todays-stock-market-news-events-12-8-2021

----- Example 3 -----
Should receive:
Interest rate hike needed 'shortly' after March 

What I receive when using your pod:
Interest rate hike needed &#39;shortly&#39; after March 

https://www.marketwatch.com/story/interest-rate-hike-needed-shortly-after-march-end-to-asset-purchases-feds-waller-says-11639764021

**Comment by Spencer-Villarreal** [comment]
Wow, Github automatically changes the Unicode to the apostrophe. My question may look weird by the main thing is that the apostrophes are still in Unicode

**Comment by khanlou** [comment]
I was noticing this too — I think this library should probably be the one to handle this conversion, rather than putting it on every caller
